options:
  install-cuda:
    type: boolean
    default: false
    description: |
      Install the CUDA binaries if capable hardware is present. This option
      is False by default, as not all applications support GPU acceleration.
